### ISSUE TITLE
java sdk dom4j 存在安全漏洞

### ISSUE THREAD

**Issue by leshalv** [aliyun/tea-xml#54]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/30397655/166154991-2ef45012-c800-448f-89c6-d668c389ff82.png">

dom4j 1.6.1 存在安全隐患，且dom4j 工件已迁移至 [org.dom4j](https://mvnrepository.com/artifact/org.dom4j) » [dom4j](https://mvnrepository.com/artifact/org.dom4j/dom4j)，请尽快更新。

```xml
<dependency>
    <groupId>org.dom4j</groupId>
    <artifactId>dom4j</artifactId>
    <version>${latest}</version>
</dependency>
```

**Comment by yndu13** [comment]
已处理
